### ISSUE TITLE
Polling the device for motor status is inconsistent.

### ISSUE THREAD

**Issue by bhavyangupta** [scanse/sweep-arduino#5]
Hi!
I am working on a custom microcontroller driver for the Sweep and I am facing some issues. First of here's the version info:
```
Version info(Output if IV command): I,V,S,W,E,E,P,1,1,1,2,1,0,0,0,0,2,1,5,2,
```
So I have an application where visual confirmation of the lidar state ( i.e. the green / blue led ) is not possible and so the configuration of the lidar must be synced via serial communication only. Here's the code that I am using to query the motor state:

```   
   char cmd[] = {'M', 'Z', '\n'};
    //Serial1.println(cmd);
    serial_port_->write(cmd, 3);
    serial_port_->flush();
    delay(500);    // This delay seems to be critical
    char response[5];
    uint32_t bytes_read = serial_port_->readBytes(response, 5);
```
The behavior I get is the following: when I remove the `delay(500)` line the lidar sends a garbled up response to the request  / or the request times out (timeout set to 1s), However, with the delay in place, everything seems to work. Is there a reason that this delay needs to be there ? My application is relatively time-sensitive so delays like these bring down the efficiency of the whole system and I'd like to avoid that. Here's the output in the two cases:

Without `delay(500)`:

```
[Lidar]Resetting
[Lidar]Setting RPM
MZ // Request message
 �W
Read: 5 // Read 5 bytes
,H,`,,�,  // Response

[Lidar]Setting RPM
MZ
 �W
Read: 5
,u,,H,d,
u
[Lidar]Setting RPM
MZ
 �W
Read: 5
,�,,r,,

[Lidar]Setting RPM
MZ
 �W
Read: 5
H,g,,�,,
Hg
```

With `delay(500)`:

```
[Lidar]Setting RPM
MZ // Request
 �W
Read: 5 // Read 5 bytes
M,Z,0,1, // Response
,
MZ01
)
[Lidar]Setting RPM
MZ
 �W
Read: 5
M,Z,0,1,
,
MZ01
)
[Lidar]Setting RPM
MZ
 �W
Read: 5
M,Z,0,1,
,
MZ01
)
[Lidar]Setting RPM
MZ
 �W
Read: 5
M,Z,0,1,
,
MZ01
)
[Lidar]Setting RPM
MZ
 �W
Read: 5
M,Z,0,1,
,
MZ01
)
[Lidar]Setting RPM
MZ
 �W
Read: 5
M,Z,0,1,
,
MZ01
)
[Lidar]Setting RPM
MZ
 �W
Read: 5
M,Z,0,1,
,
MZ01
)
[Lidar]Setting RPM
MZ
 �W
Read: 5
M,Z,0,1,
,
MZ01
)
[Lidar]Setting RPM
MZ
 �W
Read: 5
M,Z,0,1,
,
MZ01
)
[Lidar]Setting RPM
MZ
 �W
Read: 5
M,Z,0,1,
,
MZ01
)
[Lidar]Setting RPM
MZ
 �W
Read: 5
M,Z,0,1,
,
MZ01
)
[Lidar]Setting RPM
MZ
 �W
Read: 5
M,Z,0,1,

```

**Comment by dcyoung** [comment]
Hmmm. A few things to start:

> Version info(Output if IV command): I,V,S,W,E,E,P,1,1,1,2,1,0,0,0,0,2,1,5,2,

Can you [upgrade your firmware](https://support.scanse.io/hc/en-us/articles/224557908-Upgrading-Firmware) to the latest before doing anything else.

This shouldn't be relevant, but I'm curious as your device is reporting hardware version 1. Were you an early backer of Sweep that received the previous hardware version with the shorter base? 

As for the behavior you are seeing, I'm not quite sure what you mean by:
```
[Lidar]Resetting
[Lidar]Setting RPM
MZ // Request message
```
Does this mean that your program is:
1. Performing a reset on the Sweep (`RR` command).
2. Setting the motor speed (`MS` command)
3. Requesting motor ready (`MZ` command)

Do you receive a valid response to step 2 (should require that you wait long enough between steps 1 and 2 for the device to finish resetting).  After validating the sensor's response to step 2, are then having issues with receiving a response from step 3? Or are you not validating the response from step 2?

In general, you could write a simple method to check if the sensor is finished resetting by attempting to communicate with it and checking for a valid response. I'd recommend testing with a simple command that does not require the motor be stable yet, such as  `LI`.

**Comment by bhavyangupta** [comment]
Hi @dcyoung It looks like the firmware update fixed the issue. Thanks for the input! I'll close this issue and if it comes back up again I'll open a new one with more information.
